import("//third_party/closure_compiler/compile_js.gni")
import("//tools/polymer/html_to_js.gni")
import("../os_settings.gni")

polymer_element_files = [
  "jemaos_account.js",
  "jemaos_drivers.js",
  "jemaos_more_info.js",
  "jemaos_remoting.js",
  "jemaos_tweak_ui.js",
  "jemaos_experiment.js",
  "os_jema_page.js",
  "components/backup_intro_dialog.js",
  "components/backup_password_prompt_dialog.js",
  "components/restore_password_dialog.js",
  "components/restore_result_dialog.js", 
]

js_type_check("closure_compile_module") {
  closure_flags = os_settings_closure_flags
  is_polymer3 = true
  deps = [
    ":shell_client",
    ":jemaos_account",
    ":jemaos_drivers",
    ":jemaos_remoting",
    ":jemaos_more_info",
    ":jemaos_tweak_ui",
    ":jemaos_experiment",
    ":os_jema_page",
    ":backup_intro_dialog",
    ":backup_password_prompt_dialog",
    ":restore_password_dialog",
    ":restore_result_dialog", 
  ]
}

js_library("shell_client") {
  deps = [
    "//ui/webui/resources/js:cr.m"
  ]
}

js_library("jemaos_account") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
    "//ui/webui/resources/js:cr.m",
    "../os_people_page:account_manager_browser_proxy",
    "//ui/webui/resources/js:load_time_data.m",
    "//ui/webui/resources/js:web_ui_listener_behavior.m",
    "//ui/webui/resources/cr_elements/chromeos/cr_picture:png",
    "//ui/webui/resources/js:icon",
  ]
}

js_library("restore_result_dialog") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
  ]
}

js_library("jemaos_drivers") {
  deps = [
    "..:os_route",
    "../..:router",
    "..:route_observer_behavior",
    ":shell_client",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
     "//ui/webui/resources/js:web_ui_listener_behavior.m",
  ]
}

js_library("jemaos_remoting") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
    "..:os_route",
    "../..:router",
    ":shell_client",
  ]
}

js_library("jemaos_more_info") {
  deps = [
    "../os_about_page:about_page_browser_proxy",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
  ]
}

js_library("jemaos_tweak_ui") {
  deps = [
    "..:route_observer_behavior",
     "//ui/webui/resources/js:cr.m",
     "//ui/webui/resources/js:load_time_data.m",
     "//ui/webui/resources/js:i18n_behavior.m",
     "//ui/webui/resources/js:web_ui_listener_behavior.m",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    ":shell_client",
  ]
}

js_library("jemaos_experiment") {
  deps = [
    "//ui/webui/resources/js:cr.m",
    "//ui/webui/resources/js:load_time_data.m",
    "../..:lifetime_browser_proxy",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
  ]
}

js_library("os_jema_page") {
  deps = [
    "//ash/webui/common/resources:i18n_behavior",
    "..:route_observer_behavior",
  ]
}

js_library("backup_intro_dialog") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
  ]
}

js_library("backup_password_prompt_dialog") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
  ]
}

js_library("restore_file_dialog") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
  ]
}

js_library("restore_password_dialog") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
  ]
}

html_to_js("web_components") {
  js_files = polymer_element_files
}
